### ISSUE TITLE
I try to change from flexbox to carousel in smartphone screen only.

### ISSUE THREAD

**Issue by Ntsoccer** [Ntsoccer/recruitment-responsive#1]
On the screen of the smartphone, flexbox was used to line up the images of the achivement vertically, but I thought this would be a hassle for the user.
So I decided to change it to a horizontal scroll slide.
I solve this issues to use swiper.js.
It Applies only to smartphone screens.

**Comment by oladhari** [comment]
@Ntsoccer could you explain this issue?
and write a checklist describing how you are going to proceed?

**Comment by Ntsoccer** [comment]
On the screen of the smartphone, flexbox was used to line up the images of the achivement vertically, but I thought this would be a hassle for the user.
So I decided to change it to a horizontal scroll slide.
I solve this issues to use swiper.js.
It Applies only to smartphone screens.
